---
version: '3.3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
        environment:
            discovery.type: single-node
            cluster.name: es-docker-cluster
            bootstrap.memory_lock: 'true'
            discovery.seed_hosts: elasticsearch
            ES_JAVA_OPTS: -Xms512m -Xmx512m
        ulimits:
            memlock:
                soft: -1
                hard: -1
        #volumes:
        #    - data01:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:7.6.0
        deploy:
            mode: replicated
            replicas: 1
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
            - 5601:5601